name: linter

on:
  push:

permissions:
  contents: read

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: actions/setup-go@v6
        with:
          go-version-file: 'go.mod'
      - name: Install task
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: go-task/task
          cache: enable
          # tag: 
      - name: Install golangci-lint
        uses: jaxxstorm/action-install-gh-release@v2.1.0
        with:
          repo: golangci/golangci-lint
          tag: v2.8.0
          cache: enable
          binaries-location: golangci-lint-2.8.0-linux-amd64

      - name: Run linter
        shell: /usr/bin/bash {0}
        run: |
          task lint